const brothers = [
  {
    'name': 'Rishi Dhanaraj',
    'position': 'Regent',
    'eboard': true,
    'class': 'xi',
    'className': 'Xi Class',
    'major': 'cs',
    'majorName': 'Computer Science',
    'year': 'Class of 2019',
    'linkedin': 'https://www.linkedin.com/in/rdhanaraj/',
    'messenger': 'https://m.me/rishi.dhanaraj/',
    'image': require('./images/brothers/casual/rishi.webp'),
    'safari': require('./images/brothers/casual/rishi.jpg'),
    'professional': require('./images/brothers/professional/rishi.webp'),
  },
  {
    'name': 'Sherman Yip',
    'position': 'Vice Regent',
    'eboard': true,
    'class': 'xi',
    'className': 'Xi Class',
    'major': 'mech',
    'majorName': 'Mechanical Engineering',
    'year': 'Class of 2018',
    'linkedin': 'https://www.linkedin.com/in/sherman-yip-8a40b47a/',
    'messenger': 'https://m.me/ayyeHOMES/',
    'image': require('./images/brothers/casual/sherman.webp'),
    'safari': require('./images/brothers/casual/sherman.jpg'),
    'professional': require('./images/brothers/professional/sherman.webp'),
  },
  {
    'name': 'Daviid Perez',
    'position': 'Corresponding Secretary',
    'eboard': true,
    'class': 'mu',
    'className': 'Mu Class',
    'major': 'chem',
    'majorName': 'Chemical Engineering',
    'year': 'Class of 2018',
    'linkedin': 'https://www.linkedin.com/in/david-perez-aguilar-01400aba/',
    'messenger': 'https://m.me/daviiid.prz/',
    'image': require('./images/brothers/casual/daviid.webp'),
    'safari': require('./images/brothers/casual/daviid.jpg'),
    'professional': require('./images/brothers/professional/daviid.webp'),
  },
  {
    'name': 'Tyler Ly',
    'position': 'Treasurer',
    'eboard': true,
    'class': 'xi',
    'className': 'Xi Class',
    'major': 'cs',
    'majorName': 'Computer Science',
    'year': 'Class of 2018',
    'linkedin': 'https://www.linkedin.com/in/tylerly/',
    'messenger': 'https://m.me/tylerly96/',
    'image': require('./images/brothers/casual/tyler.webp'),
    'safari': require('./images/brothers/casual/tyler.jpg'),
    'professional': require('./images/brothers/professional/tyler.webp'),
  },
  {
    'name': 'Jennie Nguyen',
    'position': 'Scribe',
    'eboard': true,
    'class': 'xi',
    'className': 'Xi Class',
    'major': 'env',
    'majorName': 'Environmental Engineering',
    'year': 'Class of 2018',
    'linkedin': 'https://www.linkedin.com/in/jennie-nguyen-82a78294/',
    'messenger': 'https://m.me/jerbss/',
    'image': require('./images/brothers/casual/jennie.webp'),
    'safari': require('./images/brothers/casual/jennie.jpg'),
    'professional': require('./images/brothers/professional/jennie.webp'),
  },
  {
    'name': 'Daniel Zhang',
    'position': 'Brotherhood Chair',
    'cabinet': true,
    'class': 'nu',
    'className': 'Nu Class',
    'major': 'cs',
    'majorName': 'Computer Science',
    'year': 'Class of 2018',
    'linkedin': 'https://www.linkedin.com/in/dwzhang/',
    'image': require('./images/brothers/casual/mayuki.webp'),
    'safari': require('./images/brothers/casual/mayuki.jpg'),
    'professional': require('./images/brothers/professional/dzhang.webp'),
  },
  {
    'name': 'Mayuki Sasagawa',
    'position': 'Brotherhood Chair',
    'cabinet': true,
    'class': 'omicron',
    'className': 'Omicron Class',
    'major': 'env',
    'majorName': 'Environmental Engineering',
    'year': 'Class of 2019',
    'linkedin': 'https://www.linkedin.com/in/mayuki-a-sasagawa-a09623103/',
    'image': require('./images/brothers/casual/mayuki.webp'),
    'safari': require('./images/brothers/casual/mayuki.jpg'),
    'professional': require('./images/brothers/professional/mayuki.webp'),
  },
  {
    'name': 'Jessica Tran',
    'position': 'External Events Chair',
    'cabinet': true,
    'class': 'mu',
    'className': 'Mu Class',
    'major': 'cs',
    'majorName': 'Computer Science',
    'year': 'Class of 2018',
    'linkedin': 'https://www.linkedin.com/in/jessicantran/',
    'image': require('./images/brothers/casual/mayuki.webp'),
    'safari': require('./images/brothers/casual/mayuki.jpg'),
    'professional': require('./images/brothers/professional/jessica.webp'),
  },
  {
    'name': 'Aamir Rasheed',
    'position': 'Fundraising Chair',
    'cabinet': true,
    'class': 'omicron',
    'className': 'Omicron Class',
    'major': 'ce',
    'majorName': 'Computer Engineering',
    'year': 'Class of 2018',
    'linkedin': 'https://www.linkedin.com/in/aamir1rasheed/',
    'image': require('./images/brothers/casual/mayuki.webp'),
    'safari': require('./images/brothers/casual/mayuki.jpg'),
    'professional': require('./images/brothers/professional/aamir.webp'),
  },
  {
    'name': 'Rachael Wong',
    'position': 'Fundraising Chair',
    'cabinet': true,
    'class': 'omicron',
    'className': 'Omicron Class',
    'major': 'bio',
    'majorName': 'Bioengineering',
    'year': 'Class of 2018',
    'linkedin': 'https://www.linkedin.com/in/rachael-sze-nga-wong-9b0100129/',
    'image': require('./images/brothers/casual/mayuki.webp'),
    'safari': require('./images/brothers/casual/mayuki.jpg'),
    'professional': require('./images/brothers/professional/rachael.webp'),
  },
  {
    'name': 'Esther Park',
    'position': 'Philanthropy Chair',
    'cabinet': true,
    'class': 'xi',
    'className': 'Xi Class',
    'major': 'env',
    'majorName': 'Environmental Engineering',
    'year': 'Class of 2019',
    'linkedin': 'https://www.linkedin.com/in/esther-park/',
    'image': require('./images/brothers/casual/mayuki.webp'),
    'safari': require('./images/brothers/casual/mayuki.jpg'),
    'professional': require('./images/brothers/professional/esther.webp'),
  },
  {
    'name': 'Aston Khor',
    'position': 'Professional Chair',
    'cabinet': true,
    'class': 'pi',
    'className': 'Pi Class',
    'major': 'chem',
    'majorName': 'Chemical Engineering',
    'year': 'Class of 2018',
    'linkedin': 'https://www.linkedin.com/in/aston-khor-402b4110a/',
    'image': require('./images/brothers/casual/mayuki.webp'),
    'safari': require('./images/brothers/casual/mayuki.jpg'),
    'professional': require('./images/brothers/professional/aston.webp'),
  },
  {
    'name': 'Fumika Takazawa',
    'position': 'Professionalism Chair',
    'cabinet': true,
    'class': 'omicron',
    'className': 'Omicron Class',
    'major': 'mech',
    'majorName': 'Environmental Engineering',
    'year': 'Class of 2018',
    'linkedin': 'https://www.linkedin.com/in/ftakazawa/',
    'image': require('./images/brothers/casual/mayuki.webp'),
    'safari': require('./images/brothers/casual/mayuki.jpg'),
    'professional': require('./images/brothers/professional/fumika.webp'),
  },
  {
    'name': 'Ming Ming Liu',
    'position': 'Rush Chair',
    'cabinet': true,
    'class': 'mu',
    'className': 'Mu Class',
    'major': 'mech',
    'majorName': 'Mechanical Engineering',
    'year': 'Class of 2018',
    'linkedin': 'https://www.linkedin.com/in/kellieliu/',
    'messenger': 'https://m.me/mingming.liu.5283/',
    'image': require('./images/brothers/casual/ming.webp'),
    'safari': require('./images/brothers/casual/ming.jpg'),
    'professional': require('./images/brothers/professional/ming.webp'),
  },
  {
    'name': 'Momina Mahmood',
    'position': 'Rush Chair',
    'cabinet': true,
    'class': 'xi',
    'className': 'Xi Class',
    'major': 'chem',
    'majorName': 'Chemical Engineering',
    'year': 'Class of 2019',
    'linkedin': 'https://www.linkedin.com/in/mominamahmood/',
    'messenger': 'https://m.me/momina.mahmood.9/',
    'image': require('./images/brothers/casual/momina.webp'),
    'safari': require('./images/brothers/casual/momina.jpg'),
    'professional': require('./images/brothers/professional/momina.webp'),
  },
  {
    'name': 'Crystal Munive',
    'position': 'Special Events Chair',
    'cabinet': true,
    'class': 'mu',
    'className': 'Mu Class',
    'major': 'aero',
    'majorName': 'Aerospace Engineering',
    'year': 'Class of 2018',
    'linkedin': 'https://www.linkedin.com/in/crystal-munive-b01204149/',
    'image': require('./images/brothers/casual/mayuki.webp'),
    'safari': require('./images/brothers/casual/mayuki.jpg'),
    'professional': require('./images/brothers/professional/crystal.webp'),
  },
  {
    'name': 'Brian Chan',
    'position': 'Webmaster',
    'cabinet': true,
    'class': 'omicron',
    'className': 'Omicron Class',
    'major': 'cs',
    'majorName': 'Computer Science',
    'year': 'Class of 2019',
    'linkedin': 'https://www.linkedin.com/in/brian-chan-1020/',
    'messenger': 'https://m.me/bciscool/',
    'image': require('./images/brothers/casual/bchan.webp'),
    'safari': require('./images/brothers/casual/bchan.jpg'),
    'professional': require('./images/brothers/professional/bchan.webp'),
  },
  {
    'name': 'Kaiser Kim',
    'position': 'Webmaster',
    'cabinet': true,
    'class': 'lambda',
    'className': 'Lambda Class',
    'major': 'ce',
    'majorName': 'Computer Engineering',
    'year': 'Class of 2017',
    'linkedin': 'www.linkedin.com/in/kaiserkim/',
    'messenger': 'https://m.me/kaiser.b.kim/',
    'image': require('./images/brothers/casual/kaiser.webp'),
    'safari': require('./images/brothers/casual/kaiser.jpg'),
    'professional': require('./images/brothers/professional/kaiser.webp'),
  },
  {
    'name': 'Jeffrey Lee',
    'position': 'Active',
    'class': 'pi',
    'className': 'Pi Class',
    'major': 'cs',
    'majorName': 'Computer Science',
    'year': 'Class of 2019',
    'linkedin': 'https://www.linkedin.com/in/jeffreyzlee/',
    'messenger': 'https://m.me/MagicRiceMan/',
    'image': require('./images/brothers/casual/jeffrey.webp'),
    'safari': require('./images/brothers/casual/jeffrey.jpg'),
    'professional': require('./images/brothers/professional/jeffrey.webp'),
  },
  {
    'name': 'Hillary Fan',
    'position': 'Active',
    'class': 'pi',
    'className': 'Pi Class',
    'major': 'cs',
    'majorName': 'Computer Science',
    'year': 'Class of 2019',
    'linkedin': 'https://www.linkedin.com/in/hillary-fan-ba13b8104/',
    'messenger': 'https://m.me/hilbofan/',
    'image': require('./images/brothers/casual/hillary.webp'),
    'safari': require('./images/brothers/casual/hillary.jpg'),
    'professional': require('./images/brothers/professional/hillary.webp'),
  },
  {
    'name': 'Blake Huynh',
    'position': 'Active',
    'class': 'lambda',
    'className': 'Lambda Class',
    'major': 'ee',
    'majorName': 'Electrical Engineering',
    'year': 'Class of 2017',
    'linkedin': 'https://www.linkedin.com/in/bhhuynh/',
    'messenger': 'https://m.me/blake.huynh.1/',
    'image': require('./images/brothers/casual/blake.webp'),
    'safari': require('./images/brothers/casual/blake.jpg'),
    'professional': require('./images/brothers/professional/blake.webp'),
  },
  {
    'name': 'Leng Kouv',
    'position': 'Active',
    'class': 'omicron',
    'className': 'Omicron Class',
    'major': 'bio',
    'majorName': 'Bioengineering',
    'year': 'Class of 2019',
    'linkedin': 'https://www.linkedin.com/in/sivleng-kouv-6510b8129/',
    'messenger': 'https://m.me/leng.kouv/',
    'image': require('./images/brothers/casual/leng.webp'),
    'safari': require('./images/brothers/casual/leng.jpg'),
    'professional': require('./images/brothers/professional/leng.webp'),
  },
  {
    'name': 'Jason Li',
    'position': 'Active',
    'class': 'pi',
    'className': 'Pi Class',
    'major': 'env',
    'majorName': 'Environmental Engineering',
    'year': 'Class of 2018',
    'linkedin': 'https://www.linkedin.com/in/jason-li-7b946746/',
    'messenger': 'https://m.me/jasonjava/',
    'image': require('./images/brothers/casual/jason.webp'),
    'safari': require('./images/brothers/casual/jason.jpg'),
    'professional': require('./images/brothers/professional/jason.webp'),
  },
  {
    'name': 'Audrey Olson',
    'position': 'Active',
    'class': 'nu',
    'className': 'Nu Class',
    'major': 'cs',
    'majorName': 'Computer Science',
    'year': 'Class of 2018',
    'linkedin': 'https://www.linkedin.com/in/audreyolson/',
    'messenger': 'https://m.me/audols/',
    'image': require('./images/brothers/casual/audrey.webp'),
    'safari': require('./images/brothers/casual/audrey.jpg'),
    'professional': require('./images/brothers/professional/audrey.webp'),
  },
  {
    'name': 'Adam Lin',
    'position': 'Active',
    'class': 'pi',
    'className': 'Pi Class',
    'major': 'me',
    'majorName': 'Mechanical Engineering',
    'year': 'Class of 2020',
    'linkedin': 'https://www.linkedin.com/in/adam-lin-539655139/',
    'messenger': 'https://m.me/notadamlin/',
    'image': require('./images/brothers/casual/adam.webp'),
    'safari': require('./images/brothers/casual/adam.jpg'),
    'professional': require('./images/brothers/professional/adam.webp'),
  },
  {
    'name': 'Chetu Khandavilli',
    'position': 'Active',
    'class': 'nu',
    'className': 'Nu Class',
    'major': 'nano',
    'majorName': 'Nanoengineering',
    'year': 'Class of 2019',
    'linkedin': 'https://www.linkedin.com/in/jennie-nguyen-82a78294/',
    'messenger': 'https://m.me/100009619688323/',
    'image': require('./images/brothers/casual/chetu.webp'),
    'safari': require('./images/brothers/casual/chetu.jpg'),
    'professional': require('./images/brothers/professional/chetu.webp'),
  },
  {
    'name': 'Chelsea Jan',
    'position': 'Active',
    'class': 'mu',
    'className': 'Mu Class',
    'major': 'bio',
    'majorName': 'Bioengineering',
    'year': 'Class of 2017',
    'linkedin': 'https://www.linkedin.com/in/chelseajan/',
    'messenger': 'https://m.me/chelsea.jan.58/',
    'image': require('./images/brothers/casual/chelsea.webp'),
    'safari': require('./images/brothers/casual/chelsea.jpg'),
    'professional': require('./images/brothers/professional/chelsea.webp'),
  },
  {
    'name': 'John Tayag',
    'position': 'Active',
    'class': 'pi',
    'className': 'Pi Class',
    'major': 'me',
    'majorName': 'Mechanical Engineering',
    'year': 'Class of 2018',
    'linkedin': 'https://www.linkedin.com/in/john-tayag-325a05133/',
    'messenger': 'https://m.me/Jaunty.JohnT/',
    'image': require('./images/brothers/casual/john.webp'),
    'safari': require('./images/brothers/casual/john.jpg'),
    'professional': require('./images/brothers/professional/john.webp'),
  },
  {
    'name': 'Michael Wang',
    'position': 'Active',
    'class': 'mu',
    'className': 'Mu Class',
    'major': 'env',
    'majorName': 'Environmental Engineering',
    'year': 'Class of 2018',
    'linkedin': 'https://www.linkedin.com/in/michael-wang-99428147/',
    'messenger': 'https://m.me/swagmasterchewy/',
    'image': require('./images/brothers/casual/mwang.webp'),
    'safari': require('./images/brothers/casual/mwang.jpg'),
    'professional': require('./images/brothers/professional/mwang.webp'),
  },
  {
    'name': 'Victoria Tam',
    'position': 'Active',
    'class': 'pi',
    'className': 'Pi Class',
    'major': 'bio',
    'majorName': 'Bioengineering',
    'year': 'Class of 2019',
    'linkedin': 'https://www.linkedin.com/in/victoria-tam-2b5052117/',
    'messenger': 'https://m.me/victoria.tam.12/',
    'image': require('./images/brothers/casual/victoria.webp'),
    'safari': require('./images/brothers/casual/victoria.jpg'),
    'professional': require('./images/brothers/professional/victoria.webp'),
  },
  {
    'name': 'Shangway Hsu',
    'position': 'Active',
    'class': 'pi',
    'className': 'Pi Class',
    'major': 'cs',
    'majorName': 'Computer Science',
    'year': 'Class of 2018',
    'linkedin': 'https://www.linkedin.com/in/shangwayhsu/',
    'messenger': 'https://m.me/shangway/',
    'image': require('./images/brothers/casual/shangway.webp'),
    'safari': require('./images/brothers/casual/shangway.jpg'),
    'professional': require('./images/brothers/professional/shangway.webp'),
  },
  {
    'name': 'Brian Lyu',
    'position': 'Active',
    'class': 'xi',
    'className': 'Xi Class',
    'major': 'ce',
    'majorName': 'Computer Engineering',
    'year': 'Class of 2018',
    'linkedin': 'https://www.linkedin.com/in/brian-lyu/',
    'messenger': 'https://m.me/brian.lyu1/',
    'image': require('./images/brothers/casual/blyu.webp'),
    'safari': require('./images/brothers/casual/blyu.jpg'),
    'professional': require('./images/brothers/professional/blyu.webp'),
  },
  {
    'name': 'Wendy Lin',
    'position': 'Active',
    'class': 'lambda',
    'className': 'Lambda Class',
    'major': 'mech',
    'majorName': 'Mechanical Engineering',
    'year': 'Class of 2017',
    'linkedin': 'https://www.linkedin.com/in/wendy-lin-80489bbb/',
    'image': require('./images/brothers/casual/mayuki.webp'),
    'safari': require('./images/brothers/casual/mayuki.jpg'),
    'professional': require('./images/brothers/professional/wendy.webp'),
  },
  {
    'name': 'Claire Li',
    'position': 'Active',
    'class': 'lambda',
    'className': 'Lambda Class',
    'major': 'cs',
    'majorName': 'Computer Science',
    'year': 'Class of 2018',
    'linkedin': 'https://www.linkedin.com/in/claireli100/',
    'image': require('./images/brothers/casual/mayuki.webp'),
    'safari': require('./images/brothers/casual/mayuki.jpg'),
    'professional': require('./images/brothers/professional/claire.webp'),
  },
  {
    'name': 'Alex Tunchez',
    'position': 'Active',
    'class': 'lambda',
    'className': 'Lambda Class',
    'major': 'aero',
    'majorName': 'Aerospace Engineering',
    'year': 'Class of 2017',
    'linkedin': 'https://www.linkedin.com/in/alex-tunchez-0a2ba5127/',
    'image': require('./images/brothers/casual/mayuki.webp'),
    'safari': require('./images/brothers/casual/mayuki.jpg'),
    'professional': require('./images/brothers/professional/atunchez.webp'),
  },
  {
    'name': 'Judy Ho',
    'position': 'Active',
    'class': 'nu',
    'className': 'Nu Class',
    'major': 'cs',
    'majorName': 'Computer Science',
    'year': 'Class of 2018',
    'linkedin': 'https://www.linkedin.com/in/judy-ho-425941ab/',
    'image': require('./images/brothers/casual/mayuki.webp'),
    'safari': require('./images/brothers/casual/mayuki.jpg'),
    'professional': require('./images/brothers/professional/judy.webp'),
  },
  {
    'name': 'Adrian Gutierrez',
    'position': 'Active',
    'class': 'nu',
    'className': 'Nu Class',
    'major': 'env',
    'majorName': 'Environmental Engineering',
    'year': 'Class of 2018',
    'linkedin': 'https://www.linkedin.com/in/adrian-gutierrez-400a85bb/',
    'image': require('./images/brothers/casual/mayuki.webp'),
    'safari': require('./images/brothers/casual/mayuki.jpg'),
    'professional': require('./images/brothers/professional/adrian.webp'),
  },
  {
    'name': 'Marilyn Sun',
    'position': 'Active',
    'class': 'xi',
    'className': 'Xi Class',
    'major': 'env',
    'majorName': 'Environmental Engineering',
    'year': 'Class of 2018',
    'linkedin': 'https://www.linkedin.com/in/marilyn-sun-3677494a/',
    'image': require('./images/brothers/casual/mayuki.webp'),
    'safari': require('./images/brothers/casual/mayuki.jpg'),
    'professional': require('./images/brothers/professional/marilyn.webp'),
  },
  {
    'name': 'Goutham Marimuthu',
    'position': 'Active',
    'class': 'omicron',
    'className': 'Omicron Class',
    'major': 'mech',
    'majorName': 'Mechanical Engineering',
    'year': 'Class of 2019',
    'linkedin': 'https://www.linkedin.com/in/goutham-marimuthu-3393b3120/',
    'image': require('./images/brothers/casual/mayuki.webp'),
    'safari': require('./images/brothers/casual/mayuki.jpg'),
    'professional': require('./images/brothers/professional/goutham.webp'),
  },
  {
    'name': 'Manwinder Uppal',
    'position': 'Active',
    'class': 'omicron',
    'className': 'Omicron Class',
    'major': 'env',
    'majorName': 'Environmental Engineering',
    'year': 'Class of 2018',
    'linkedin': 'https://www.linkedin.com/in/manwinder-uppal-311861109/',
    'image': require('./images/brothers/casual/mayuki.webp'),
    'safari': require('./images/brothers/casual/mayuki.jpg'),
    'professional': require('./images/brothers/professional/money.webp'),
  },
  {
    'name': 'Justin Dulay',
    'position': 'Active',
    'class': 'omicron',
    'className': 'Omicron Class',
    'major': 'struct',
    'majorName': 'Structural Engineering',
    'year': 'Class of 2019',
    'linkedin': 'https://www.linkedin.com/in/justin-dulay-9a7b74123/',
    'image': require('./images/brothers/casual/mayuki.webp'),
    'safari': require('./images/brothers/casual/mayuki.jpg'),
    'professional': require('./images/brothers/professional/jdulay.webp'),
  },
  {
    'name': 'Wonjae Lee',
    'position': 'Active',
    'class': 'omicron',
    'className': 'Omicron Class',
    'major': 'chem',
    'majorName': 'Chemical Engineering',
    'year': 'Class of 2018',
    'linkedin': 'https://www.linkedin.com/in/wonjae-lee-b017b7132/',
    'image': require('./images/brothers/casual/mayuki.webp'),
    'safari': require('./images/brothers/casual/mayuki.jpg'),
    'professional': require('./images/brothers/professional/wonjae.webp'),
  },
  {
    'name': 'Kevin Huo',
    'position': 'Active',
    'class': 'pi',
    'className': 'Pi Class',
    'major': 'env',
    'majorName': 'Environmental Engineering',
    'year': 'Class of 2018',
    'linkedin': 'https://www.linkedin.com/in/kevin--huo/',
    'image': require('./images/brothers/casual/mayuki.webp'),
    'safari': require('./images/brothers/casual/mayuki.jpg'),
    'professional': require('./images/brothers/professional/khuo.webp'),
  },
  {
    'name': 'Allen Gao',
    'position': 'Active',
    'class': 'pi',
    'className': 'Pi Class',
    'major': 'cs',
    'majorName': 'Computer Science',
    'year': 'Class of 2019',
    'linkedin': 'https://www.linkedin.com/in/agao323/',
    'image': require('./images/brothers/casual/mayuki.webp'),
    'safari': require('./images/brothers/casual/mayuki.jpg'),
    'professional': require('./images/brothers/professional/allen.webp'),
  },
  {
    'name': 'Ana Dasgupta',
    'position': 'Active',
    'class': 'pi',
    'className': 'Pi Class',
    'major': 'env',
    'majorName': 'Environmental Engineering',
    'year': 'Class of 2020',
    'linkedin': 'https://www.linkedin.com/in/anahita-dasgupta-788a29133/',
    'image': require('./images/brothers/casual/mayuki.webp'),
    'safari': require('./images/brothers/casual/mayuki.jpg'),
    'professional': require('./images/brothers/professional/ana.webp'),
  },
  {
    'name': 'Stephanie Zhu',
    'position': 'Active',
    'class': 'pi',
    'className': 'Pi Class',
    'major': 'env',
    'majorName': 'Environmental Engineering',
    'year': 'Class of 2020',
    'image': require('./images/brothers/casual/mayuki.webp'),
    'safari': require('./images/brothers/casual/mayuki.jpg'),
    'professional': require('./images/brothers/professional/stephanie.webp'),
  },
  {
    'name': 'Geoffrey Ngo',
    'position': 'Active',
    'class': 'pi',
    'className': 'Pi Class',
    'major': 'mech',
    'majorName': 'Mechanical Engineering',
    'year': 'Class of 2019',
    'image': require('./images/brothers/casual/mayuki.webp'),
    'safari': require('./images/brothers/casual/mayuki.jpg'),
    'professional': require('./images/brothers/professional/geoffrey.webp'),
  },
  {
    'name': 'Meghna Satish',
    'position': 'Active',
    'class': 'pi',
    'className': 'Pi Class',
    'major': 'cs',
    'majorName': 'Math - Computer Science',
    'year': 'Class of 2019',
    'image': require('./images/brothers/casual/mayuki.webp'),
    'safari': require('./images/brothers/casual/mayuki.jpg'),
    'professional': require('./images/brothers/professional/meghna.webp'),
  },
]

const alumni = [
  {
    'name': 'Aeri Iamsirithaworn',
    'professional': require('./images/brothers/alumni/aeri_iamsirithaworn.webp'),
    'position': 'Alumni',
    'class': 'iota',
    'className': 'Iota Class',
    'majorName': 'Computer Science',
  },
  {
    'name': 'Andrew Sie',
    'professional': require('./images/brothers/alumni/andrew_sie.webp'),
    'position': 'Alumni',
    'class': 'iota',
    'className': 'Iota Class',
    'majorName': 'Computer Science',
  },
  {
    'name': 'Azhar Deen',
    'professional': require('./images/brothers/alumni/azhar_deen.webp'),
    'position': 'Alumni',
    'class': 'iota',
    'className': 'Iota Class',
    'majorName': 'Computer Science',
  },
  {
    'name': 'Best Tech',
    'professional': require('./images/brothers/alumni/bchan.webp'),
    'position': 'Alumni',
    'class': 'charter',
    'className': 'Charter Class',
    'majorName': 'Computer Science'
  },
  {
    'name': 'Michael Luo',
    'professional': require('./images/brothers/alumni/michael_luo.webp'),
    'position': 'Alumni',
    'class': 'iota',
    'className': 'Iota Class',
    'majorName': 'Computer Science',
  },
  {
    'name': 'Patrick Chen',
    'professional': require('./images/brothers/alumni/patrick_chen.webp'),
    'position': 'Alumni',
    'class': 'iota',
    'className': 'Iota Class',
    'majorName': 'Computer Science',
  },
  {
    'name': 'Sharon Zheng',
    'professional': require('./images/brothers/alumni/sharon_zheng.webp'),
    'position': 'Alumni',
    'class': 'iota',
    'className': 'Iota Class',
    'majorName': 'Computer Science',
  },
  {
    'name': 'Thomas Kuo',
    'professional': require('./images/brothers/alumni/thomas_kuo.webp'),
    'position': 'Alumni',
    'class': 'iota',
    'className': 'Iota Class',
    'majorName': 'Computer Science',
  },
  {
    'name': 'Woongkee Min',
    'professional': require('./images/brothers/alumni/woongkee_min.webp'),
    'position': 'Alumni',
    'class': 'iota',
    'className': 'Iota Class',
    'majorName': 'Computer Science',
  },
  {
    'name': 'Yutang Lin',
    'professional': require('./images/brothers/alumni/yutang_lin.webp'),
    'position': 'Alumni',
    'class': 'iota',
    'className': 'Iota Class',
    'majorName': 'Computer Science',
  },
]

const options = {
  general: [
    { value: 'active', label: 'Active' },
    { value: 'major', label: 'Major' },
    { value: 'class', label: 'Class' },
    // { value: 'alumni', label: 'Alumni' },
  ],
  active: [
    { value: 'eboard', label: 'Executive Board' },
    { value: 'cabinet', label: 'Cabinet' },
  ],
  major: [
    { 
      value: 'aero', 
      label: 'Aerospace Engineering',
      image: require('./images/majors/logos/aero.png'),
    },
    { 
      value: 'bio', 
      label: 'Bioengineering',
      image: require('./images/majors/logos/bio.png'), 
    },
    { 
      value: 'chem', 
      label: 'Chemical Engineering',
      image: require('./images/majors/logos/chem.png'), 
    },
    { 
      value: 'ce', 
      label: 'Computer Engineering',
      image: require('./images/majors/logos/ce.png'), 
    },
    { 
      value: 'cs', 
      label: 'Computer Science', 
      image: require('./images/majors/logos/ce.png'),
    },
    { 
      value: 'ee', 
      label: 'Electrical Engineering',
      image: require('./images/majors/logos/ee.png'), 
    },
    { 
      value: 'env', 
      label: 'Environmental Engineering',
      image: require('./images/majors/logos/env.png'), 
    },
    { 
      value: 'mech', 
      label: 'Mechanical Engineering',
      image: require('./images/majors/logos/mech.png'), 
    },
    { 
      value: 'nano', 
      label: 'Nanoengineering',
      image: require('./images/majors/logos/nano.png'), 
    },
    { 
      value: 'struct', 
      label: 'Structural Engineering',
      image: require('./images/majors/logos/struct.png'), 
    },
  ],
  class: [
    { 
      value: 'charter', 
      label: 'Charter',
      image: require('./images/classes/letters/charter.jpg'),
    },
    { 
      value: 'alpha', 
      label: 'Alpha',
      image: require('./images/classes/letters/alpha.png'),
    },
    { 
      value: 'beta', 
      label: 'Beta',
      image: require('./images/classes/letters/beta.png'),
    },
    { 
      value: 'gamma', 
      label: 'Gamma',
      image: require('./images/classes/letters/gamma.png'), 
    },
    { 
      value: 'delta', 
      label: 'Delta',
      image: require('./images/classes/letters/delta.png'), 
    },
    { 
      value: 'epsilon', 
      label: 'Epsilon',
      image: require('./images/classes/letters/epsilon.png'), 
    },
    { 
      value: 'zeta', 
      label: 'Zeta',
      image: require('./images/classes/letters/zeta.png'), 
    },
    { 
      value: 'eta', 
      label: 'Eta',
      image: require('./images/classes/letters/eta.png'), 
    },
    { 
      value: 'theta', 
      label: 'Theta',
      image: require('./images/classes/letters/theta.png'), 
    },
    { 
      value: 'iota', 
      label: 'Iota',
      image: require('./images/classes/letters/iota.png'), 
    },
    { 
      value: 'kappa', 
      label: 'Kappa',
      image: require('./images/classes/letters/kappa.png'), 
    },
    { 
      value: 'lambda', 
      label: 'Lambda',
      image: require('./images/classes/letters/lambda.png'), 
    },
    { 
      value: 'mu', 
      label: 'Mu',
      image: require('./images/classes/letters/mu.png'), 
    },
    { 
      value: 'nu', 
      label: 'Nu',
      image: require('./images/classes/letters/nu.png'), 
    },
    { 
      value: 'xi', 
      label: 'Xi',
      image: require('./images/classes/letters/xi.png'), 
    },
    { 
      value: 'omicron', 
      label: 'Omicron',
      image: require('./images/classes/letters/omicron.png'), 
    },
    { 
      value: 'pi', 
      label: 'Pi',
      image: require('./images/classes/letters/pi.png'), 
    },
  ]
}

const images = [
  {
    'name': 'active',
    'url': require('./images/general/active.jpg'),
  },
  {
    'name': 'major',
    'url': require('./images/general/major.jpg'),
  },
  {
    'name': 'class',
    'url': require('./images/general/active.jpg'),
  },
  {
    'name': 'alumni',
    'url': require('./images/general/alumni.jpg'),
  },
  {
    'name': 'eboard',
    'url': require('./images/general/active.jpg'),
  },
  {
    'name': 'cabinet',
    'url': require('./images/general/active.jpg'),
  },
  {
    'name': 'cs',
    'url': require('./images/majors/images/cs.jpg'),
  },
  {
    'name': 'aero',
    'url': require('./images/majors/images/aero.jpg'),
  },
  {
    'name': 'mech',
    'url': require('./images/majors/images/mech-struct.jpg'),
  },
  {
    'name': 'env',
    'url': require('./images/majors/images/env.jpg'),
  },
  {
    'name': 'ce',
    'url': require('./images/majors/images/cs.jpg'),
  },
  {
    'name': 'bio',
    'url': require('./images/majors/images/bio.jpg'),
  },
  {
    'name': 'chem',
    'url': require('./images/majors/images/chem.jpg'),
  },
  {
    'name': 'ee',
    'url': require('./images/majors/images/ee.jpg'),
  },
  {
    'name': 'struct',
    'url': require('./images/majors/images/mech-struct.jpg'),
  },
  {
    'name': 'nano',
    'url': require('./images/majors/images/chem.jpg'),
  },
  {
    'name': 'charter',
    'url': require('./images/classes/images/charter.jpg'),
  },
  {
    'name': 'alpha',
    'url': require('./images/classes/images/alpha.jpg'),
  },
  {
    'name': 'beta',
    'url': require('./images/classes/images/charter.jpg'),
  },
  {
    'name': 'gamma',
    'url': require('./images/classes/images/gamma.jpg'),
  },
  {
    'name': 'delta',
    'url': require('./images/classes/images/delta.jpg'),
  },
  {
    'name': 'epsilon',
    'url': require('./images/classes/images/epsilon.jpg'),
  },
  {
    'name': 'zeta',
    'url': require('./images/classes/images/zeta.jpg'),
  },
  {
    'name': 'eta',
    'url': require('./images/classes/images/eta.jpg'),
  },
  {
    'name': 'theta',
    'url': require('./images/classes/images/theta.jpg'),
  },
  {
    'name': 'iota',
    'url': require('./images/classes/images/iota.jpg'),
  },
  {
    'name': 'kappa',
    'url': require('./images/classes/images/kappa.jpg'),
  },
  {
    'name': 'lambda',
    'url': require('./images/classes/images/lambda.jpg'),
  },
  {
    'name': 'mu',
    'url': require('./images/classes/images/mu.jpg'),
  },
  {
    'name': 'nu',
    'url': require('./images/classes/images/nu.jpg'),
  },
  {
    'name': 'xi',
    'url': require('./images/classes/images/xi.jpg'),
  },
  {
    'name': 'omicron',
    'url': require('./images/classes/images/omicron.jpg'),
  },
  {
    'name': 'pi',
    'url': require('./images/classes/images/pi.jpg'),
  },
]

export {brothers, alumni, options, images};