const brothers = [
  {
    'name': 'Rishi Dhanaraj',
    'position': 'Regent',
    'eboard': true,
    'class': 'xi',
    'className': 'Xi Class',
    'major': 'cs',
    'majorName': 'Computer Science',
    'year': 'Class of 2019',
    'linkedin': 'https://www.linkedin.com/in/kaiser-kim-8aa1b011b/',
    'messenger': 'https://m.me/rishi.dhanaraj/',
    'image': require('./images/brothers/casual/rishi.webp'),
    'safari': require('./images/brothers/casual/rishi.jpg'),
    'url': require('./images/brothers/professional/rishi.webp'),
  },
  {
    'name': 'Sherman Yip',
    'position': 'Vice Regent',
    'eboard': true,
    'class': 'xi',
    'className': 'Xi Class',
    'major': 'mech',
    'majorName': 'Mechanical Engineering',
    'year': 'Class of 2018',
    'linkedin': 'https://www.linkedin.com/in/kaiser-kim-8aa1b011b/',
    'messenger': 'https://m.me/ayyeHOMES/',
    'image': require('./images/brothers/casual/sherman.webp'),
    'safari': require('./images/brothers/casual/sherman.jpg'),
    'url': require('./images/brothers/professional/sherman.webp'),
  },
  {
    'name': 'Daviid Perez',
    'position': 'Corresponding Secretary',
    'eboard': true,
    'class': 'mu',
    'className': 'Mu Class',
    'major': 'chem',
    'majorName': 'Chemical Engineering',
    'year': 'Class of 2018',
    'linkedin': 'https://www.linkedin.com/in/kaiser-kim-8aa1b011b/',
    'messenger': 'https://m.me/daviiid.prz/',
    'image': require('./images/brothers/casual/daviid.webp'),
    'safari': require('./images/brothers/casual/daviid.jpg'),
    'url': require('./images/brothers/professional/daviid.webp'),
  },
  {
    'name': 'Tyler Ly',
    'position': 'Treasurer',
    'eboard': true,
    'class': 'xi',
    'className': 'Xi Class',
    'major': 'cs',
    'majorName': 'Computer Science',
    'year': 'Class of 2018',
    'linkedin': 'https://www.linkedin.com/in/kaiser-kim-8aa1b011b/',
    'messenger': 'https://m.me/tylerly96/',
    'image': require('./images/brothers/casual/tyler.webp'),
    'safari': require('./images/brothers/casual/tyler.jpg'),
    'url': require('./images/brothers/professional/tyler.webp'),
  },
  {
    'name': 'Jennie Nguyen',
    'position': 'Scribe',
    'eboard': true,
    'class': 'xi',
    'className': 'Xi Class',
    'major': 'env',
    'majorName': 'Environmental Engineering',
    'year': 'Class of 2018',
    'linkedin': 'https://www.linkedin.com/in/kaiser-kim-8aa1b011b/',
    'messenger': 'https://m.me/jerbss/',
    'image': require('./images/brothers/casual/jennie.webp'),
    'safari': require('./images/brothers/casual/jennie.jpg'),
    'url': require('./images/brothers/professional/jennie.webp'),
  },
  {
    'name': 'Brian Chan',
    'position': 'Webmaster',
    'cabinet': true,
    'class': 'omicron',
    'className': 'Omicron Class',
    'major': 'cs',
    'majorName': 'Computer Science',
    'year': 'Class of 2019',
    'messenger': 'https://m.me/bciscool/',
    'image': require('./images/brothers/casual/bchan.webp'),
    'safari': require('./images/brothers/casual/bchan.jpg'),
    'url': require('./images/brothers/professional/bchan.webp'),
  },
  {
    'name': 'Kaiser Kim',
    'position': 'Webmaster',
    'cabinet': true,
    'class': 'lambda',
    'className': 'Lambda Class',
    'major': 'ce',
    'majorName': 'Computer Engineering',
    'year': 'Class of 2017',
    'messenger': 'https://m.me/kaiser.b.kim/',
    'image': require('./images/brothers/casual/kaiser.webp'),
    'safari': require('./images/brothers/casual/kaiser.jpg'),
    'url': require('./images/brothers/professional/kaiser.webp'),
  },
  {
    'name': 'Momina Mahmood',
    'position': 'Rush Chair',
    'class': 'xi',
    'className': 'Xi Class',
    'major': 'chem',
    'majorName': 'Chemical Engineering',
    'year': 'Class of 2019',
    'messenger': 'https://m.me/momina.mahmood.9/',
    'image': require('./images/brothers/casual/momina.webp'),
    'safari': require('./images/brothers/casual/momina.jpg'),
    'url': require('./images/brothers/professional/momina.webp'),
  },
  {
    'name': 'Ming Ming Liu',
    'position': 'Rush Chair',
    'class': 'mu',
    'className': 'Mu Class',
    'major': 'mech',
    'majorName': 'Mechanical Engineering',
    'year': 'Class of 2018',
    'messenger': 'https://m.me/mingming.liu.5283/',
    'image': require('./images/brothers/casual/ming.webp'),
    'safari': require('./images/brothers/casual/ming.jpg'),
    'url': require('./images/brothers/professional/ming.webp'),
  },
  {
    'name': 'Jeffrey Lee',
    'position': 'Active',
    'class': 'pi',
    'className': 'Pi Class',
    'major': 'cs',
    'majorName': 'Computer Science',
    'year': 'Class of 2019',
    'messenger': 'https://m.me/MagicRiceMan/',
    'image': require('./images/brothers/casual/jeffrey.webp'),
    'safari': require('./images/brothers/casual/jeffrey.jpg'),
    'url': require('./images/brothers/professional/jeffrey.webp'),
  },
  {
    'name': 'Hillary Fan',
    'position': 'Active',
    'class': 'pi',
    'className': 'Pi Class',
    'major': 'cs',
    'majorName': 'Computer Science',
    'year': 'Class of 2019',
    'messenger': 'https://m.me/hilbofan/',
    'image': require('./images/brothers/casual/hillary.webp'),
    'safari': require('./images/brothers/casual/hillary.jpg'),
    'url': require('./images/brothers/professional/hillary.webp'),
  },
  {
    'name': 'Blake Huynh',
    'position': 'Active',
    'class': 'lambda',
    'className': 'Lambda Class',
    'major': 'ee',
    'majorName': 'Electrical Engineering',
    'year': 'Class of 2017',
    'messenger': 'https://m.me/blake.huynh.1/',
    'image': require('./images/brothers/casual/blake.webp'),
    'safari': require('./images/brothers/casual/blake.jpg'),
    'url': require('./images/brothers/professional/blake.webp'),
  },
  {
    'name': 'Leng Kouv',
    'position': 'Active',
    'class': 'omicron',
    'className': 'Omicron Class',
    'major': 'bio',
    'majorName': 'Bioengineering',
    'year': 'Class of 2019',
    'messenger': 'https://m.me/leng.kouv/',
    'image': require('./images/brothers/casual/leng.webp'),
    'safari': require('./images/brothers/casual/leng.jpg'),
    'url': require('./images/brothers/professional/leng.webp'),
  },
  {
    'name': 'Jason Li',
    'position': 'Active',
    'class': 'pi',
    'className': 'Pi Class',
    'major': 'env',
    'majorName': 'Environmental Engineering',
    'year': 'Class of 2018',
    'messenger': 'https://m.me/jasonjava/',
    'image': require('./images/brothers/casual/jason.webp'),
    'safari': require('./images/brothers/casual/jason.jpg'),
    'url': require('./images/brothers/professional/jason.webp'),
  },
  {
    'name': 'Audrey Olson',
    'position': 'Active',
    'class': 'nu',
    'className': 'Nu Class',
    'major': 'cs',
    'majorName': 'Computer Science',
    'year': 'Class of 2018',
    'messenger': 'https://m.me/audols/',
    'image': require('./images/brothers/casual/audrey.webp'),
    'safari': require('./images/brothers/casual/audrey.jpg'),
    'url': require('./images/brothers/professional/audrey.webp'),
  },
  {
    'name': 'Adam Lin',
    'position': 'Active',
    'class': 'pi',
    'className': 'Pi Class',
    'major': 'ee',
    'majorName': 'Electrical Engineering',
    'year': 'Class of 2020',
    'messenger': 'https://m.me/notadamlin/',
    'image': require('./images/brothers/casual/adam.webp'),
    'safari': require('./images/brothers/casual/adam.jpg'),
    'url': require('./images/brothers/professional/adam.webp'),
  },
  {
    'name': 'Chetu Khandavilli',
    'position': 'Active',
    'class': 'nu',
    'className': 'Nu Class',
    'major': 'nano',
    'majorName': 'Nanoengineering',
    'year': 'Class of 2019',
    'messenger': 'https://m.me/100009619688323/',
    'image': require('./images/brothers/casual/chetu.webp'),
    'safari': require('./images/brothers/casual/chetu.jpg'),
    'url': require('./images/brothers/professional/chetu.webp'),
  },
  {
    'name': 'Chelsea Jan',
    'position': 'Active',
    'class': 'mu',
    'className': 'Mu Class',
    'major': 'bio',
    'majorName': 'Bioengineering',
    'year': 'Class of 2017',
    'messenger': 'https://m.me/chelsea.jan.58/',
    'image': require('./images/brothers/casual/chelsea.webp'),
    'safari': require('./images/brothers/casual/chelsea.jpg'),
    'url': require('./images/brothers/professional/chelsea.webp'),
  },
  {
    'name': 'John Tayag',
    'position': 'Active',
    'class': 'pi',
    'className': 'Pi Class',
    'major': 'ee',
    'majorName': 'Electrical Engineering',
    'year': 'Class of 2018',
    'messenger': 'https://m.me/Jaunty.JohnT/',
    'image': require('./images/brothers/casual/john.webp'),
    'safari': require('./images/brothers/casual/john.jpg'),
    'url': require('./images/brothers/professional/john.webp'),
  },
  {
    'name': 'Michael Wang',
    'position': 'Active',
    'class': 'mu',
    'className': 'Mu Class',
    'major': 'env',
    'majorName': 'Environmental Engineering',
    'year': 'Class of 2018',
    'messenger': 'https://m.me/swagmasterchewy/',
    'image': require('./images/brothers/casual/michael.webp'),
    'safari': require('./images/brothers/casual/michael.jpg'),
    'url': require('./images/brothers/professional/michael.webp'),
  },
  {
    'name': 'Victoria Tam',
    'position': 'Active',
    'class': 'pi',
    'className': 'Pi Class',
    'major': 'bio',
    'majorName': 'Bioengineering',
    'year': 'Class of 2019',
    'messenger': 'https://m.me/victoria.tam.12/',
    'image': require('./images/brothers/casual/victoria.webp'),
    'safari': require('./images/brothers/casual/victoria.jpg'),
    'url': require('./images/brothers/professional/victoria.webp'),
  },
  {
    'name': 'Shangway Hsu',
    'position': 'Active',
    'class': 'pi',
    'className': 'Pi Class',
    'major': 'cs',
    'majorName': 'Computer Science',
    'year': 'Class of 2018',
    'messenger': 'https://m.me/shangway/',
    'image': require('./images/brothers/casual/shangway.webp'),
    'safari': require('./images/brothers/casual/shangway.jpg'),
    'url': require('./images/brothers/professional/shangway.webp'),
  },
  {
    'name': 'Brian Lyu',
    'position': 'Active',
    'class': 'xi',
    'className': 'Xi Class',
    'major': 'ce',
    'majorName': 'Computer Engineering',
    'year': 'Class of 2018',
    'messenger': 'https://m.me/brian.lyu1/',
    'image': require('./images/brothers/casual/blyu.webp'),
    'safari': require('./images/brothers/casual/blyu.jpg'),
    'url': require('./images/brothers/professional/blyu.webp'),
  },
  {
    'name': 'Mayuki Sasagawa',
    'position': 'Active',
    'class': 'omicron',
    'className': 'Omicron Class',
    'major': 'env',
    'majorName': 'Environmental Engineering',
    'year': 'Class of 2019',
    'messenger': 'https://m.me/myuki.sasagawa/',
    'image': require('./images/brothers/casual/mayuki.webp'),
    'safari': require('./images/brothers/casual/mayuki.jpg'),
    'url': require('./images/brothers/professional/mayuki.webp'),
  },
]

const alumni = [
  {
    'name': 'Aeri Iamsirithaworn',
    'url': require('./images/brothers/alumni/aeri_iamsirithaworn.webp'),
    'position': 'Alumni',
    'class': 'iota',
    'className': 'Iota Class',
    'majorName': 'Computer Science',
  },
  {
    'name': 'Andrew Sie',
    'url': require('./images/brothers/alumni/andrew_sie.webp'),
    'position': 'Alumni',
    'class': 'iota',
    'className': 'Iota Class',
    'majorName': 'Computer Science',
  },
  {
    'name': 'Azhar Deen',
    'url': require('./images/brothers/alumni/azhar_deen.webp'),
    'position': 'Alumni',
    'class': 'iota',
    'className': 'Iota Class',
    'majorName': 'Computer Science',
  },
  {
    'name': 'Best Tech',
    'url': require('./images/brothers/alumni/bchan.webp'),
    'position': 'Alumni',
    'class': 'charter',
    'className': 'Charter Class',
    'majorName': 'Computer Science'
  },
  {
    'name': 'Michael Luo',
    'url': require('./images/brothers/alumni/michael_luo.webp'),
    'position': 'Alumni',
    'class': 'iota',
    'className': 'Iota Class',
    'majorName': 'Computer Science',
  },
  {
    'name': 'Patrick Chen',
    'url': require('./images/brothers/alumni/patrick_chen.webp'),
    'position': 'Alumni',
    'class': 'iota',
    'className': 'Iota Class',
    'majorName': 'Computer Science',
  },
  {
    'name': 'Sharon Zheng',
    'url': require('./images/brothers/alumni/sharon_zheng.webp'),
    'position': 'Alumni',
    'class': 'iota',
    'className': 'Iota Class',
    'majorName': 'Computer Science',
  },
  {
    'name': 'Thomas Kuo',
    'url': require('./images/brothers/alumni/thomas_kuo.webp'),
    'position': 'Alumni',
    'class': 'iota',
    'className': 'Iota Class',
    'majorName': 'Computer Science',
  },
  {
    'name': 'Woongkee Min',
    'url': require('./images/brothers/alumni/woongkee_min.webp'),
    'position': 'Alumni',
    'class': 'iota',
    'className': 'Iota Class',
    'majorName': 'Computer Science',
  },
  {
    'name': 'Yutang Lin',
    'url': require('./images/brothers/alumni/yutang_lin.webp'),
    'position': 'Alumni',
    'class': 'iota',
    'className': 'Iota Class',
    'majorName': 'Computer Science',
  },
]

const options = {
  general: [
    { value: 'active', label: 'Active' },
    { value: 'major', label: 'Major' },
    { value: 'class', label: 'Class' },
    { value: 'alumni', label: 'Alumni' },
  ],
  active: [
    { value: 'eboard', label: 'Executive Board' },
    { value: 'cabinet', label: 'Cabinet' },
  ],
  major: [
    { 
      value: 'aero', 
      label: 'Aerospace Engineering',
      image: require('./images/majors/logos/aero.png'),
    },
    { 
      value: 'bio', 
      label: 'Bioengineering',
      image: require('./images/majors/logos/bio.png'), 
    },
    { 
      value: 'chem', 
      label: 'Chemical Engineering',
      image: require('./images/majors/logos/chem.png'), 
    },
    { 
      value: 'ce', 
      label: 'Computer Engineering',
      image: require('./images/majors/logos/ce.png'), 
    },
    { 
      value: 'cs', 
      label: 'Computer Science', 
      image: require('./images/majors/logos/ce.png'),
    },
    { 
      value: 'ee', 
      label: 'Electrical Engineering',
      image: require('./images/majors/logos/ee.png'), 
    },
    { 
      value: 'env', 
      label: 'Environmental Engineering',
      image: require('./images/majors/logos/env.png'), 
    },
    { 
      value: 'mech', 
      label: 'Mechanical Engineering',
      image: require('./images/majors/logos/mech.png'), 
    },
    { 
      value: 'nano', 
      label: 'Nanoengineering',
      image: require('./images/majors/logos/nano.png'), 
    },
    { 
      value: 'struct', 
      label: 'Structural Engineering',
      image: require('./images/majors/logos/struct.png'), 
    },
  ],
  class: [
    { 
      value: 'charter', 
      label: 'Charter',
      image: require('./images/classes/letters/charter.jpg'),
    },
    { 
      value: 'alpha', 
      label: 'Alpha',
      image: require('./images/classes/letters/alpha.png'),
    },
    { 
      value: 'beta', 
      label: 'Beta',
      image: require('./images/classes/letters/beta.png'),
    },
    { 
      value: 'gamma', 
      label: 'Gamma',
      image: require('./images/classes/letters/gamma.png'), 
    },
    { 
      value: 'delta', 
      label: 'Delta',
      image: require('./images/classes/letters/delta.png'), 
    },
    { 
      value: 'epsilon', 
      label: 'Epsilon',
      image: require('./images/classes/letters/epsilon.png'), 
    },
    { 
      value: 'zeta', 
      label: 'Zeta',
      image: require('./images/classes/letters/zeta.png'), 
    },
    { 
      value: 'eta', 
      label: 'Eta',
      image: require('./images/classes/letters/eta.png'), 
    },
    { 
      value: 'theta', 
      label: 'Theta',
      image: require('./images/classes/letters/theta.png'), 
    },
    { 
      value: 'iota', 
      label: 'Iota',
      image: require('./images/classes/letters/iota.png'), 
    },
    { 
      value: 'kappa', 
      label: 'Kappa',
      image: require('./images/classes/letters/kappa.png'), 
    },
    { 
      value: 'lambda', 
      label: 'Lambda',
      image: require('./images/classes/letters/lambda.png'), 
    },
    { 
      value: 'mu', 
      label: 'Mu',
      image: require('./images/classes/letters/mu.png'), 
    },
    { 
      value: 'nu', 
      label: 'Nu',
      image: require('./images/classes/letters/nu.png'), 
    },
    { 
      value: 'xi', 
      label: 'Xi',
      image: require('./images/classes/letters/xi.png'), 
    },
    { 
      value: 'omicron', 
      label: 'Omicron',
      image: require('./images/classes/letters/omicron.png'), 
    },
    { 
      value: 'pi', 
      label: 'Pi',
      image: require('./images/classes/letters/pi.png'), 
    },
  ]
}

const images = [
  {
    'name': 'active',
    'url': require('./images/general/active.jpg'),
  },
  {
    'name': 'major',
    'url': require('./images/general/major.jpg'),
  },
  {
    'name': 'class',
    'url': require('./images/general/active.jpg'),
  },
  {
    'name': 'alumni',
    'url': require('./images/general/alumni.jpg'),
  },
  {
    'name': 'eboard',
    'url': require('./images/general/active.jpg'),
  },
  {
    'name': 'cabinet',
    'url': require('./images/general/active.jpg'),
  },
  {
    'name': 'cs',
    'url': require('./images/majors/images/cs.jpg'),
  },
  {
    'name': 'aero',
    'url': require('./images/majors/images/aero.jpg'),
  },
  {
    'name': 'mech',
    'url': require('./images/majors/images/mech-struct.jpg'),
  },
  {
    'name': 'env',
    'url': require('./images/majors/images/env.jpg'),
  },
  {
    'name': 'ce',
    'url': require('./images/majors/images/cs.jpg'),
  },
  {
    'name': 'bio',
    'url': require('./images/majors/images/bio.jpg'),
  },
  {
    'name': 'chem',
    'url': require('./images/majors/images/chem.jpg'),
  },
  {
    'name': 'ee',
    'url': require('./images/majors/images/ee.jpg'),
  },
  {
    'name': 'struct',
    'url': require('./images/majors/images/mech-struct.jpg'),
  },
  {
    'name': 'nano',
    'url': require('./images/majors/images/chem.jpg'),
  },
  {
    'name': 'charter',
    'url': require('./images/classes/images/charter.jpg'),
  },
  {
    'name': 'alpha',
    'url': require('./images/classes/images/alpha.jpg'),
  },
  {
    'name': 'beta',
    'url': require('./images/classes/images/charter.jpg'),
  },
  {
    'name': 'gamma',
    'url': require('./images/classes/images/gamma.jpg'),
  },
  {
    'name': 'delta',
    'url': require('./images/classes/images/delta.jpg'),
  },
  {
    'name': 'epsilon',
    'url': require('./images/classes/images/epsilon.jpg'),
  },
  {
    'name': 'zeta',
    'url': require('./images/classes/images/zeta.jpg'),
  },
  {
    'name': 'eta',
    'url': require('./images/classes/images/eta.jpg'),
  },
  {
    'name': 'theta',
    'url': require('./images/classes/images/theta.jpg'),
  },
  {
    'name': 'iota',
    'url': require('./images/classes/images/iota.jpg'),
  },
  {
    'name': 'kappa',
    'url': require('./images/classes/images/kappa.jpg'),
  },
  {
    'name': 'lambda',
    'url': require('./images/classes/images/lambda.jpg'),
  },
  {
    'name': 'mu',
    'url': require('./images/classes/images/mu.jpg'),
  },
  {
    'name': 'nu',
    'url': require('./images/classes/images/nu.jpg'),
  },
  {
    'name': 'xi',
    'url': require('./images/classes/images/xi.jpg'),
  },
  {
    'name': 'omicron',
    'url': require('./images/classes/images/omicron.jpg'),
  },
  {
    'name': 'pi',
    'url': require('./images/classes/images/pi.jpg'),
  },
]

export {brothers, alumni, options, images};