const brothers = [
  {
    'name': 'Rishi Dhanaraj',
    'url': require('./images/brothers/rishi.jpg'),
    'position': 'Regent',
    'eboard': true,
    'class': 'charter',
    'className': 'Charter Class',
    'major': 'cs',
    'majorName': 'Computer Science',
    'year': 'Class of 2019',
    'linkedin': 'https://www.linkedin.com/in/kaiser-kim-8aa1b011b/',
  },
  {
    'name': 'Brian Chan',
    'url': require('./images/brothers/bchan.jpg'),
    'position': 'Chair',
    'cabinet': true,
    'class': 'alpha',
    'className': 'Alpha Class',
    'major': 'bio',
    'majorName': 'Bioengineering',
    'year': 'Class of 2019',
  },
  {
    'name': 'Jeffrey Lee',
    'url': require('./images/brothers/jeffrey.jpg'),
    'position': 'Chair',
    'class': 'beta',
    'className': 'Beta Class',
    'major': 'env',
    'majorName': 'Environmental Engineering',
    'year': 'Class of 2019',
  },
  {
    'name': 'Hillary Fan',
    'url': require('./images/brothers/hillary.jpg'),
    'position': 'Chair',
    'class': 'gamma',
    'className': 'Gamma Class',
    'major': 'ee',
    'majorName': 'Electrical Engineering',
    'year': 'Class of 2019',
  },
  {
    'name': 'Kaiser Kim',
    'url': require('./images/brothers/bchan.jpg'),
    'position': 'Active',
    'cabinet': true,
    'class': 'delta',
    'className': 'Delta Class',
    'major': 'aero',
    'majorName': 'Aerospace Engineering',
    'year': 'Class of 2019',
  },
  {
    'name': 'Blake Huynh',
    'url': require('./images/brothers/bchan.jpg'),
    'position': 'Active',
    'class': 'epsilon',
    'className': 'Epsilon Class',
    'major': 'mech',
    'majorName': 'Mechanical Engineering',
    'year': 'Class of 2019',
  },
  {
    'name': 'Hodor',
    'url': require('./images/brothers/bchan.jpg'),
    'position': 'Active',
    'class': 'zeta',
    'className': 'Zeta Class',
    'major': 'struct',
    'majorName': 'Structural Engineering',
    'year': 'Class of 2019',
  },
  {
    'name': 'Hodor',
    'url': require('./images/brothers/bchan.jpg'),
    'position': 'Active',
    'class': 'eta',
    'className': 'Eta Class',
    'major': 'ce',
    'majorName': 'Computer Engineering',
    'year': 'Class of 2019',
  },
  {
    'name': 'Hodor',
    'url': require('./images/brothers/bchan.jpg'),
    'position': 'Active',
    'class': 'theta',
    'className': 'Theta Class',
    'major': 'chem',
    'majorName': 'Chemical Engineering',
    'year': 'Class of 2019',
  },
  {
    'name': 'Hodor',
    'url': require('./images/brothers/bchan.jpg'),
    'position': 'Active',
    'class': 'pi',
    'className': 'Pi Class',
    'major': 'nano',
    'majorName': 'Nanoengineering',
    'year': 'Class of 2019',
  },
  {
    'name': 'Hodor',
    'url': require('./images/brothers/bchan.jpg'),
    'position': 'Active',
    'class': 'kappa',
    'className': 'Kappa Class',
    'major': 'cs',
    'majorName': 'Computer Science',
    'year': 'Class of 2019',
  },
  {
    'name': 'Hodor',
    'url': require('./images/brothers/bchan.jpg'),
    'position': 'Active',
    'class': 'lambda',
    'className': 'Lambda Class',
    'major': 'cs',
    'majorName': 'Computer Science',
    'year': 'Class of 2019',
  },
  {
    'name': 'Hodor',
    'url': require('./images/brothers/bchan.jpg'),
    'position': 'Active',
    'class': 'mu',
    'className': 'Mu Class',
    'major': 'cs',
    'majorName': 'Computer Science',
    'year': 'Class of 2019',
  },
  {
    'name': 'Fumika Takazawa',
    'url': require('./images/brothers/bchan.jpg'),
    'position': 'Active',
    'class': 'nu',
    'className': 'Nu Class',
    'major': 'cs',
    'majorName': 'Computer Science',
    'year': 'Class of 2019',
  },
  {
    'name': 'Hodor',
    'url': require('./images/brothers/bchan.jpg'),
    'position': 'Active',
    'class': 'xi',
    'className': 'Xi Class',
    'major': 'cs',
    'majorName': 'Computer Science',
    'year': 'Class of 2019',
  },
  {
    'name': 'Hodor',
    'url': require('./images/brothers/bchan.jpg'),
    'position': 'Active',
    'class': 'omicron',
    'className': 'Omicron Class',
    'major': 'cs',
    'majorName': 'Computer Science',
    'year': 'Class of 2019',
  },
  {
    'name': 'Hodor',
    'url': require('./images/brothers/bchan.jpg'),
    'position': 'Active',
    'class': 'pi',
    'className': 'Pi Class',
    'major': 'cs',
    'majorName': 'Computer Science',
    'year': 'Class of 2019',
  },
]

const alumni = [
  {
    'name': 'Aeri Iamsirithaworn',
    'url': require('./images/brothers/aeri_iamsirithaworn.jpg'),
    'position': 'Alumni',
    'class': 'iota',
    'className': 'Iota Class',
    'majorName': 'Computer Science',
  },
  {
    'name': 'Andrew Sie',
    'url': require('./images/brothers/andrew_sie.jpg'),
    'position': 'Alumni',
    'class': 'iota',
    'className': 'Iota Class',
    'majorName': 'Computer Science',
  },
  {
    'name': 'Azhar Deen',
    'url': require('./images/brothers/azhar_deen.jpg'),
    'position': 'Alumni',
    'class': 'iota',
    'className': 'Iota Class',
    'majorName': 'Computer Science',
  },
  {
    'name': 'Best Tech',
    'url': require('./images/brothers/bchan.jpg'),
    'position': 'Alumni',
    'class': 'charter',
    'className': 'Charter Class',
    'majorName': 'Computer Science'
  },
  {
    'name': 'Michael Luo',
    'url': require('./images/brothers/michael_luo.jpg'),
    'position': 'Alumni',
    'class': 'iota',
    'className': 'Iota Class',
    'majorName': 'Computer Science',
  },
  {
    'name': 'Patrick Chen',
    'url': require('./images/brothers/patrick_chen.jpg'),
    'position': 'Alumni',
    'class': 'iota',
    'className': 'Iota Class',
    'majorName': 'Computer Science',
  },
  {
    'name': 'Sharon Zheng',
    'url': require('./images/brothers/sharon_zheng.jpg'),
    'position': 'Alumni',
    'class': 'iota',
    'className': 'Iota Class',
    'majorName': 'Computer Science',
  },
  {
    'name': 'Thomas Kuo',
    'url': require('./images/brothers/thomas_kuo.jpg'),
    'position': 'Alumni',
    'class': 'iota',
    'className': 'Iota Class',
    'majorName': 'Computer Science',
  },
  {
    'name': 'Woongkee Min',
    'url': require('./images/brothers/woongkee_min.jpg'),
    'position': 'Alumni',
    'class': 'iota',
    'className': 'Iota Class',
    'majorName': 'Computer Science',
  },
  {
    'name': 'Yutang Lin',
    'url': require('./images/brothers/yutang_lin.jpg'),
    'position': 'Alumni',
    'class': 'iota',
    'className': 'Iota Class',
    'majorName': 'Computer Science',
  },
]

const options = {
  general: [
    { value: 'active', label: 'Active' },
    { value: 'major', label: 'Major' },
    { value: 'class', label: 'Class' },
    { value: 'alumni', label: 'Alumni' },
  ],
  active: [
    { value: 'eboard', label: 'Executive Board' },
    { value: 'cabinet', label: 'Cabinet' },
  ],
  major: [
    { 
      value: 'aero', 
      label: 'Aerospace Engineering',
      image: require('./images/majors/logos/aero.png'),
    },
    { 
      value: 'bio', 
      label: 'Bioengineering',
      image: require('./images/majors/logos/bio.png'), 
    },
    { 
      value: 'chem', 
      label: 'Chemical Engineering',
      image: require('./images/majors/logos/chem.png'), 
    },
    { 
      value: 'ce', 
      label: 'Computer Engineering',
      image: require('./images/majors/logos/ce.png'), 
    },
    { 
      value: 'cs', 
      label: 'Computer Science', 
      image: require('./images/majors/logos/ce.png'),
    },
    { 
      value: 'ee', 
      label: 'Electrical Engineering',
      image: require('./images/majors/logos/ee.png'), 
    },
    { 
      value: 'env', 
      label: 'Environmental Engineering',
      image: require('./images/majors/logos/env.png'), 
    },
    { 
      value: 'mech', 
      label: 'Mechanical Engineering',
      image: require('./images/majors/logos/mech.png'), 
    },
    { 
      value: 'nano', 
      label: 'Nanoengineering',
      image: require('./images/majors/logos/nano.png'), 
    },
    { 
      value: 'struct', 
      label: 'Structural Engineering',
      image: require('./images/majors/logos/struct.png'), 
    },
  ],
  class: [
    { 
      value: 'charter', 
      label: 'Charter',
      image: require('./images/classes/letters/charter.jpg'),
    },
    { 
      value: 'alpha', 
      label: 'Alpha',
      image: require('./images/classes/letters/alpha.png'),
    },
    { 
      value: 'beta', 
      label: 'Beta',
      image: require('./images/classes/letters/beta.png'),
    },
    { 
      value: 'gamma', 
      label: 'Gamma',
      image: require('./images/classes/letters/gamma.png'), 
    },
    { 
      value: 'delta', 
      label: 'Delta',
      image: require('./images/classes/letters/delta.png'), 
    },
    { 
      value: 'epsilon', 
      label: 'Epsilon',
      image: require('./images/classes/letters/epsilon.png'), 
    },
    { 
      value: 'zeta', 
      label: 'Zeta',
      image: require('./images/classes/letters/zeta.png'), 
    },
    { 
      value: 'eta', 
      label: 'Eta',
      image: require('./images/classes/letters/eta.png'), 
    },
    { 
      value: 'theta', 
      label: 'Theta',
      image: require('./images/classes/letters/theta.png'), 
    },
    { 
      value: 'iota', 
      label: 'Iota',
      image: require('./images/classes/letters/iota.png'), 
    },
    { 
      value: 'kappa', 
      label: 'Kappa',
      image: require('./images/classes/letters/kappa.png'), 
    },
    { 
      value: 'lambda', 
      label: 'Lambda',
      image: require('./images/classes/letters/lambda.png'), 
    },
    { 
      value: 'mu', 
      label: 'Mu',
      image: require('./images/classes/letters/mu.png'), 
    },
    { 
      value: 'nu', 
      label: 'Nu',
      image: require('./images/classes/letters/nu.png'), 
    },
    { 
      value: 'xi', 
      label: 'Xi',
      image: require('./images/classes/letters/xi.png'), 
    },
    { 
      value: 'omicron', 
      label: 'Omicron',
      image: require('./images/classes/letters/omicron.png'), 
    },
    { 
      value: 'pi', 
      label: 'Pi',
      image: require('./images/classes/letters/pi.png'), 
    },
  ]
}

const images = [
  {
    'name': 'active',
    'url': require('./images/general/active.jpg'),
  },
  {
    'name': 'major',
    'url': require('./images/general/major.jpg'),
  },
  {
    'name': 'class',
    'url': require('./images/general/active.jpg'),
  },
  {
    'name': 'alumni',
    'url': require('./images/general/alumni.jpg'),
  },
  {
    'name': 'eboard',
    'url': require('./images/general/active.jpg'),
  },
  {
    'name': 'cabinet',
    'url': require('./images/general/active.jpg'),
  },
  {
    'name': 'cs',
    'url': require('./images/majors/images/cs.jpg'),
  },
  {
    'name': 'aero',
    'url': require('./images/majors/images/aero.jpg'),
  },
  {
    'name': 'mech',
    'url': require('./images/majors/images/mech-struct.jpg'),
  },
  {
    'name': 'env',
    'url': require('./images/majors/images/env.jpg'),
  },
  {
    'name': 'ce',
    'url': require('./images/majors/images/cs.jpg'),
  },
  {
    'name': 'bio',
    'url': require('./images/majors/images/bio.jpg'),
  },
  {
    'name': 'chem',
    'url': require('./images/majors/images/chem.jpg'),
  },
  {
    'name': 'ee',
    'url': require('./images/majors/images/ee.jpg'),
  },
  {
    'name': 'struct',
    'url': require('./images/majors/images/mech-struct.jpg'),
  },
  {
    'name': 'nano',
    'url': require('./images/majors/images/chem.jpg'),
  },
  {
    'name': 'charter',
    'url': require('./images/classes/images/charter.jpg'),
  },
  {
    'name': 'alpha',
    'url': require('./images/classes/images/alpha.jpg'),
  },
  {
    'name': 'beta',
    'url': require('./images/classes/images/charter.jpg'),
  },
  {
    'name': 'gamma',
    'url': require('./images/classes/images/gamma.jpg'),
  },
  {
    'name': 'delta',
    'url': require('./images/classes/images/delta.jpg'),
  },
  {
    'name': 'epsilon',
    'url': require('./images/classes/images/epsilon.jpg'),
  },
  {
    'name': 'zeta',
    'url': require('./images/classes/images/zeta.jpg'),
  },
  {
    'name': 'eta',
    'url': require('./images/classes/images/eta.jpg'),
  },
  {
    'name': 'theta',
    'url': require('./images/classes/images/theta.jpg'),
  },
  {
    'name': 'iota',
    'url': require('./images/classes/images/iota.jpg'),
  },
  {
    'name': 'kappa',
    'url': require('./images/classes/images/kappa.jpg'),
  },
  {
    'name': 'lambda',
    'url': require('./images/classes/images/lambda.jpg'),
  },
  {
    'name': 'mu',
    'url': require('./images/classes/images/mu.jpg'),
  },
  {
    'name': 'nu',
    'url': require('./images/classes/images/nu.jpg'),
  },
  {
    'name': 'xi',
    'url': require('./images/classes/images/xi.jpg'),
  },
  {
    'name': 'omicron',
    'url': require('./images/classes/images/omicron.jpg'),
  },
  {
    'name': 'pi',
    'url': require('./images/classes/images/pi.jpg'),
  },
]

export {brothers, alumni, options, images};